import { createCorosOAuthProvider } from './coros-oauth-provider';
import { CorosRepositoryPort } from '../domain/coros-repository.port';

function mockRepo(): jest.Mocked<CorosRepositoryPort> {
  return {
    findTokenByUser: jest.fn(),
    saveToken: jest.fn(),
    updateSyncStatus: jest.fn(),
    deleteToken: jest.fn(),
    findAllConnectedUserIds: jest.fn(),
    getOAuthClient: jest.fn(),
    saveOAuthClient: jest.fn(),
    createOAuthState: jest.fn(),
    saveCodeVerifierForState: jest.fn(),
    consumeOAuthState: jest.fn(),
  };
}

describe('createCorosOAuthProvider', () => {
  it('state() generates a state and persists it against the user before returning', async () => {
    const repo = mockRepo();
    const provider = createCorosOAuthProvider({ userId: 'user-1', repo, redirectUri: 'https://api.example.com/coros/callback' });

    const state = await provider.state!();

    expect(typeof state).toBe('string');
    expect(state.length).toBeGreaterThan(20);
    expect(repo.createOAuthState).toHaveBeenCalledWith(state, 'user-1');
  });

  it('saveCodeVerifier() attaches the verifier to the state generated by state()', async () => {
    const repo = mockRepo();
    const provider = createCorosOAuthProvider({ userId: 'user-1', repo, redirectUri: 'https://api.example.com/coros/callback' });

    const state = await provider.state!();
    await provider.saveCodeVerifier('verifier-abc');

    expect(repo.saveCodeVerifierForState).toHaveBeenCalledWith(state, 'verifier-abc');
  });

  it('saveCodeVerifier() throws if called before state()', async () => {
    const repo = mockRepo();
    const provider = createCorosOAuthProvider({ userId: 'user-1', repo, redirectUri: 'https://api.example.com/coros/callback' });

    await expect(provider.saveCodeVerifier('verifier-abc')).rejects.toThrow('unexpected SDK call order');
  });

  it('redirectToAuthorization() hands the URL to the onAuthorizationUrl callback instead of opening a browser', async () => {
    const repo = mockRepo();
    const captured: string[] = [];
    const provider = createCorosOAuthProvider({
      userId: 'user-1',
      repo,
      redirectUri: 'https://api.example.com/coros/callback',
      onAuthorizationUrl: (url) => captured.push(url),
    });

    await provider.redirectToAuthorization(new URL('https://mcpeu.coros.com/authorize?state=xyz'));

    expect(captured).toEqual(['https://mcpeu.coros.com/authorize?state=xyz']);
  });

  it('codeVerifier() returns the known verifier supplied at construction (callback phase)', async () => {
    const repo = mockRepo();
    const provider = createCorosOAuthProvider({
      userId: 'user-1',
      repo,
      redirectUri: 'https://api.example.com/coros/callback',
      knownCodeVerifier: 'stored-verifier',
    });

    await expect(provider.codeVerifier()).resolves.toBe('stored-verifier');
  });

  it('codeVerifier() throws when no known verifier was supplied (connect phase)', async () => {
    const repo = mockRepo();
    const provider = createCorosOAuthProvider({ userId: 'user-1', repo, redirectUri: 'https://api.example.com/coros/callback' });

    await expect(provider.codeVerifier()).rejects.toThrow('No code verifier available');
  });

  it('tokens()/saveTokens() round-trip through the repository, scoped to userId', async () => {
    const repo = mockRepo();
    repo.findTokenByUser.mockResolvedValue({
      id: 't1', userId: 'user-1', accessToken: 'stored-access', refreshToken: 'stored-refresh',
      expiresAt: new Date(), corosUserId: null, lastSyncAt: null, lastSuccessfulSyncAt: null,
      lastAttemptAt: null, syncStatus: 'idle', syncError: null, isExpired: false,
    } as never);
    const provider = createCorosOAuthProvider({ userId: 'user-1', repo, redirectUri: 'https://api.example.com/coros/callback' });

    const tokens = await provider.tokens();
    expect(tokens).toEqual({ access_token: 'stored-access', refresh_token: 'stored-refresh', token_type: 'Bearer' });

    await provider.saveTokens({ access_token: 'new-access', refresh_token: 'new-refresh', expires_in: 3600, token_type: 'Bearer' });
    expect(repo.saveToken).toHaveBeenCalledWith('user-1', expect.objectContaining({ accessToken: 'new-access', refreshToken: 'new-refresh' }));
  });

  it('saveTokens() preserves the previously-stored refresh token when the response omits refresh_token', async () => {
    const repo = mockRepo();
    repo.findTokenByUser.mockResolvedValue({
      id: 't1', userId: 'user-1', accessToken: 'stored-access', refreshToken: 'previously-stored-refresh',
      expiresAt: new Date(), corosUserId: null, lastSyncAt: null, lastSuccessfulSyncAt: null,
      lastAttemptAt: null, syncStatus: 'idle', syncError: null, isExpired: false,
    } as never);
    const provider = createCorosOAuthProvider({ userId: 'user-1', repo, redirectUri: 'https://api.example.com/coros/callback' });

    await provider.saveTokens({ access_token: 'new-access', token_type: 'Bearer' });

    expect(repo.saveToken).toHaveBeenCalledWith('user-1', expect.objectContaining({ accessToken: 'new-access', refreshToken: 'previously-stored-refresh' }));
  });
});
